USE ctc0096db;

SET SQL_SAFE_UPDATES=0;
CREATE TABLE MAJOR (
idMajor CHAR(4) NOT NULL,
name VARCHAR(25) NULL,
dept VARCHAR(25) NULL,
advisor VARCHAR(10) NULL,
CONSTRAINT MajorPK PRIMARY KEY(idMajor)
);
CREATE TABLE STUDENT (
idStudent INT NOT NULL,
firstname VARCHAR(10) NULL,
mi CHAR(1) NULL,
lastname VARCHAR(15) NULL,
stmajor CHAR(4) NULL,
gpa NUMERIC(4,3) DEFAULT 0,
CONSTRAINT StudentPK PRIMARY KEY(idStudent),
CONSTRAINT Major_FK FOREIGN KEY(stmajor) REFERENCES MAJOR(idMajor)
ON UPDATE NO ACTION
ON DELETE NO ACTION
);



INSERT INTO MAJOR VALUES('ACCT', 'ACCOUNTING', 'ACCOUNTING', null);
INSERT INTO MAJOR VALUES('MGMT', 'MANAGEMENT', 'MANAGEMENT', null);
INSERT INTO MAJOR VALUES('ENTR', 'ENTREPRENEURSHIP', 'MANAGEMENT', null);
INSERT INTO MAJOR VALUES('FINC', 'FINANCE', 'FINANCE', null);
INSERT INTO MAJOR VALUES('REAL', 'REAL ESTATE', 'FINANCE', null);
INSERT INTO MAJOR VALUES('ISMN', 'INFO SYSTEMS', 'SYSTEMS & TECH', null);
INSERT INTO MAJOR VALUES('BUAL', 'BUSINESS ANALYTICS', 'SYSTEMS & TECH', null);
INSERT INTO MAJOR VALUES('MRKT', 'MARKETING', 'MARKETING', null);
INSERT INTO MAJOR VALUES('SCMN', 'SUPPLY CHAIN MGMT', 'SUPPLY CHAIN MANAGEMENT', null);

INSERT INTO STUDENT VALUES(1, 'Cheryl', null, 'Ladd', 'ACCT', 3.45);
INSERT INTO STUDENT VALUES(2, 'Max', null, 'Verstappen', 'REAL', 3.2);
INSERT INTO STUDENT VALUES(3, 'Dan', 'D', 'Alden', 'SCMN', 3.80);
INSERT INTO STUDENT VALUES(4, 'Jennie', 'J', 'Mauney', 'REAL', 3.80);
INSERT INTO STUDENT VALUES(5, 'Beth', null, 'Miller', 'ACCT', 2.75);
INSERT INTO STUDENT VALUES(6, 'John', null, 'Green', 'ACCT', 2.6);
INSERT INTO STUDENT VALUES(7, 'Cosmo', 'Q', 'Kramer', 'MRKT', 2.24);
INSERT INTO STUDENT VALUES(8, 'Maisie', 'T', 'Boxer', 'ENTR', 1.78);
INSERT INTO STUDENT VALUES(9, 'Emerson', 'T', 'Boxer', 'FINC', 1.42);
INSERT INTO STUDENT VALUES(10, 'Ellie', 'T', 'Boxer', 'ACCT', 3.66);

Select * FROM STUDENT;

